name: krdpass_auth_flutter_example
description: Minimal Sign in with KRDPASS example.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  krdpass_auth_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
